info:
  contact:
    email: henri-vandersleyen@protonmail.com
    name: Henri Vandersleyen
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: BSD-3-Clause license
    url: https://opensource.org/license/bsd-3-clause/
  termsOfService: http://swagger.io/terms/
  title: Printer Exchange Api
  version: "1.0"
paths: {}
swagger: "2.0"
