apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sveltekit-frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sveltekit-frontend
subjects:
  - kind: ServiceAccount
    name: sveltekit-frontend-sa
