apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gofiber-secret
  namespace: 3d-printer-website-backend
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCLaHGO8zY53t8pDtZwxpbxWKnfY8FRSlaJunSB3V7kDvnZ23ld0gBQ/ZtuY4f9sOCQ4btsytHORsjoe13+fTdn656OVrgFHZc8pr35w10alCNb78ZjzBiOkDZkaNlZUc33surFiZpG5F0A5t3hc/P+m1KnThBvdU0hfcWMRvPV1ccJCzMuqmQBSXAU6jMIOAZ+TRsHnFJa3BBQWYCCtS7ib/jBgnD7xSLKd3X3ZUnU3hAfxFPg31RWC6gbuWSsrSuvA+0VoSX6TA5Ub5w9rys8/oU4wfGusUNG5ifx3jTP8b90evwlRpB03BnBbUafx0cczkyz/knnFF6wAggG+WqYMJXJ3Qe8RfQO6NlCuzSDpQn0A5PuFC20/s9D0gVWgkQHbuFLNzJzPYTjy1DPJ4puCxxzgiX0Pz9jYNr5SzkfBAHD1qyRTmmkP5twzFOULnYlyqkEu2DEaIetFSMKrcnBYMcw8dCLRHnkZkMWcSm/zPALdyXu3lboy34sDWVSLWwg/ccz+MRG2yQJa++dUDAB3pNxGWrcz1eXHDPetXLrQ2Ulg3TqJt/qwRiWBSaLPxYr9LqL1W83HhcYFeS3ZTqVkHMOHLz6AvPYIppJqr4cLCxBtjzpCsHF0kyO878AYcfELGO+y1alu0qiWdw4zkZEUbBRLUenkNXCUW7yhhykdRqvjBGXLZBKrR4VER2+F8qZD2wyCefgaU1U4edSw27vzZavbfTdkaKb
  template:
    metadata:
      creationTimestamp: null
      name: gofiber-secret
      namespace: 3d-printer-website-backend

