# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofiber-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: gofiber-backend
          # TODO: make a different overlays
          # image: vandercycle/3d-printer-exchange-backend
          image: localhost:5000/backend-fiber
          # envFrom:
          #   - configMapRef:
          #       name: gofiber-backend-cm
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              memory: 256Mi
          ports:
            - name: http
              containerPort: 8080
