# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: gofiber
spec:
  # type: ClusterIP
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: http
