apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patchesJson6902:
- target:
    kind: Deployment
    name: gofiber-backend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: localhost:5000/backend-fiber
