apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 3d-printer-website-frontend

commonLabels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: sveltekit
    app.kubernetes.io/name: sveltekit-frontend
    app.kubernetes.io/part-of: printer-exchange

labels:
  - pairs:
      app.kubernetes.io/component: frontend
    includeTemplates: true

resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
  - ./role.yaml
  - ./rolebinding.yaml
  - ./serviceaccount.yaml
