name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - frontend/**
      - backend/**

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker login -u "$DOCKER_USER" --password "$DOCKER_PASSWORD"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          ls -al
          # Use variables
          (cd ./backend && docker build . --tag vandercycle/3d-printer-exchange-backend:latest)
          (cd ./frontend && docker build . --tag vandercycle/3d-printer-exchange-frontend:latest)

      - name: Docker Push image
        run: |
          vandercycle/3d-printer-exchange-backend:latest
          vandercycle/3d-printer-exchange-frontend:latest
